remote_theme: just-the-docs/just-the-docs
title: smallAW's Blog
logo: "https://i.pximg.net/img-master/img/2021/08/13/00/00/18/91928468_p0_master1200.jpg"
# Color scheme supports "light" (default) and "dark"
color_scheme: light